providers = ["python"]

[phases.setup]
nixPkgs = ["chromium", "chromedriver"]

[phases.install]
cmds = ["PYTHON3_BIN=$(find /nix/store -name python3 -type f | head -1) && export PATH=$(dirname $PYTHON3_BIN):$PATH && python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python build completed'"]

[start]
cmd = "python3 smart-token-server.py"

[variables]
CHROME_BIN = "/usr/bin/chromium"
CHROMEDRIVER_PATH = "/usr/bin/chromedriver"
