providers = ["python"]

[phases.setup]
nixPkgs = ["chromium", "chromedriver"]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python build completed'"]

[start]
cmd = "python3 smart-token-server.py"

[variables]
CHROME_BIN = "/usr/bin/chromium"
CHROMEDRIVER_PATH = "/usr/bin/chromedriver"
