[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "npm install --omit=dev"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "node railway-token-server.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
CONTAINERIZED = "1"
