[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "apt-get update",
  "apt-get install -y chromium-browser",
  "npm install --only=production"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "node railway-token-server.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
CONTAINERIZED = "1"
