providers = ["python"]

[phases.setup]
nixPkgs = ["python3", "chromium", "chromedriver"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python build completed'"]

[start]
cmd = "python3 smart-token-server.py"

[variables]
CHROME_BIN = "/usr/bin/chromium"
CHROMEDRIVER_PATH = "/usr/bin/chromedriver"
